import { FormProfileType, FormScheduleType } from "../../patientTypes";

export const scheduleFormInput: FormScheduleType = {
  tujuan: {
    id: "schedule_1",
    title: "Tujuan",
    placeholder: "Tujuan penjadwalan",
    error: "Tujuan wajib dimasukkan",
    number: false,
    editable: false,
  },
  schedule_id: {
    id: "schedule_2",
    title: "ID Jadwal",
    placeholder: "Jadwal pemeriksaan",
    error: "Jadwal pemeriksaan wajib dimasukkan",
    number: false,
    editable: false,
  },
  current_phone: {
    id: "schedule_3",
    title: "Nomor Telpon yang digunakan ",
    placeholder: "Nomor Telpon Anda",
    error: "Nomor Telpon wajib dimasukkan",
    number: true,
    editable: true,
  },
  appointment_type: {
    id: "schedule_4",
    title: "Jenis Penjadwalan",
    placeholder: "Masukkan kategori penjadwalan",
    error: "",
    number: false,
    editable: false,
  },
  scheduled_date: {
    id: "schedule_5",
    title: "Jadwal Pemeriksaan",
    placeholder: "DD/MM/YYYY",
    error: "Tanggal wajib dipilih",
    number: false,
    editable: false,
  },
  register_date: {
    id: "schedule_6",
    title: "Tanggal Pendaftaran Pemeriksaan",
    placeholder: "DD/MM/YYYY",
    error: "Tanggal wajib dipilih",
    number: false,
    editable: false,
  },
  using_bpjs: {
    id: "schedule_7",
    title: "Pendaftaran menggunakan BPJS",
    placeholder: "Apakah menggunakan BPJS ",
    error: "Konfirmasi BPJS wajib dimasukkan",
    number: true,
    editable: true,
  },
  nomor_antrian: {
    id: "schedule_8",
    title: "Nomor Antrian ",
    placeholder: " Nomor BPJS boleh memilih untuk memakai atau tidak",
    error: "",
    number: true,
    editable: true,
  },
};
